project_name: github-artifact-proxy
builds:
  - env: [CGO_ENABLED=0]
    main: ./cmd/github-artifact-proxy/
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

dockers:

- image_templates: ["luqasn/github-artifact-proxy:{{ .Version }}-amd64"]
  dockerfile: Dockerfile
  use: buildx
  goarch: amd64
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/luqasn/github-artifact-proxy
  - --label=org.opencontainers.image.source=https://github.com/luqasn/github-artifact-proxy
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=AGPL-3.0

- image_templates: ["luqasn/github-artifact-proxy:{{ .Version }}-arm64v8"]
  dockerfile: Dockerfile
  use: buildx
  goarch: arm64
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/luqasn/github-artifact-proxy
  - --label=org.opencontainers.image.source=https://github.com/luqasn/github-artifact-proxy
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=AGPL-3.0

docker_manifests:
- name_template: luqasn/github-artifact-proxy:{{ .Version }}
  image_templates:
  - luqasn/github-artifact-proxy:{{ .Version }}-amd64
  - luqasn/github-artifact-proxy:{{ .Version }}-arm64v8
- name_template: luqasn/github-artifact-proxy:latest
  image_templates:
  - luqasn/github-artifact-proxy:{{ .Version }}-amd64
  - luqasn/github-artifact-proxy:{{ .Version }}-arm64v8

