http:
  bind: 0.0.0.0:8080
  base_path: /
download_dir: '.'
github:
  cache_ttl: 5m
  tokens:
    pat: ghp_your-access-token-here
targets:
  menta:
    # Required: A GitHub API token with at least the "public_repo" scope
    token: pat
    # Required: The username of the user who owns the repository
    owner: alexbakker
    # Required: The name of the repository
    repo: menta
    # Required: The workflow filename
    filename: build.yaml
    # Optional filter to apply when "latest" is passed as the workflow run ID
    latest_filter:
      # Optional: The branch name
      branch: master
      # Optional: The event that kicked off the workflow run
      event: push
      # Optional: The status with which the workflow run finished
      status: success
